apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: node-tuning
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
